# Konfigurasi dasar situs
title: Hocindo ğŸ©
description: Program Investasi Hocindo dengan desain elegan dan modern.
url: "https://hocindo.github.io" # URL situs Anda
baseurl: "" # Kosong untuk root domain
lang: id_ID # Bahasa Indonesia
layout: default
