# Konfigurasi dasar situs
title: Hocindo ğŸ©
description: Program Investasi Hocindo dengan desain elegan dan modern.
url: "https://hocindo.github.io"
baseurl: ""
lang: id_ID

# Tema
theme: minima # Akan dioverride oleh style.css
# Alternatif: theme: jekyll-theme-cayman
